baseURL = "http://highcountrygc.com/"
languageCode = "en-us"
title = "High Country General Contractors"

[params]
  titlePart1 = "High Country"
  titlePart2 = "General Contractors"
  subTitle = "Bringing South Florida construction to the High Country"
  logo = "/img/logo.png"

[[menu.main]]
  name = "Contact"
  url = "page/contact"
  weight = 1

[[menu.main]]
  name = "About"
  url = "page/about"
  weight = 2
