baseURL = "https://test.highcountrygc.com/"
languageCode = "en-us"
title = "High Country General Contractors"
publishDir = "docs"

[params]
  # subTitle = "Bringing South Florida construction to the High Country"
  logo = "/img/logo_side.png"
  favicon = "/favicon.ico"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Portfolio"
  url = "project/"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "page/contact"
  weight = 3
